### ISSUE TITLE
Local by Flywheel | Safari (MacOS)

### ISSUE THREAD

**Issue by blitzgeek** [ThemeFuse/Brizy#100]
Hi there!
Congrats for an awesome new builder.
What i have noticed so far:
1. I can't edit (change) the button text with Safari on Mac OS, it works only with Chrome.
2. I can't use it with my local environment (Local by Flywheel), the system runs out of memory and after "update" and leaving the builder, only the "header-block" is visible in regular site view. (All saved stuff is still there inside the builder).

**Comment by bagrinsergiu** [comment]
Hi @blitzgeek,

Thank you for appreciation. 

1. We have some problems with safari because we used some new technologies like CSS Variables. We don't plan to solve it soon. Please use Chrome or Firefox for edit mode. Preview mode will work fine on Safari.

2. I will test it and reply with details

Thanks for reporting
Sergiu

**Comment by bagrinsergiu** [comment]
In 1.0.19 we added 3 fixes for page compiler/ preview mode

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thanks for reporting
Sergiu
