### ISSUE TITLE
Video Background Bugs and Feature Request

### ISSUE THREAD

**Issue by sentivate** [ThemeFuse/Brizy#1067]
BUGS (I'm on a 1gbs fiber connection right near large hubs and data centers on the east coast)
- Vimeo currently doesn't autoplay the video unless I right click the page and click inspect element then it immediately starts playing.
- Youtube video as a background shows the title and topbar buttons before play begins. This of course looks obviously unprofessional and unattractive. When it loops back it shows a loading icon and a black screen before it replays again a horrible option when it comes to using it as a background.

Feature and solution
Native support for using a video URL as the background with an HTML5 player. It should auto-play and not show controls nor have sound. This is easily done and is actually a far superior option than youtube or vimeo.

**Comment by NataliaBB** [comment]
Hey @sentivate!

Apologizes for my late reply. Thanks for your message.  
First, I've added the HML5 player option in our to do list. Sergiu and the team will look over this and will find a solution how to implement in the builder.

Regarding the youtube video on background - we need to think on a more advanced module for YT iframe, because - on background mode, you can not simply remove the title and top bar, this is how their API iframe works. 

My best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
