### ISSUE TITLE
Cannot sign up for Affiliates via the Affiliate page when already a Brizy user

### ISSUE THREAD

**Issue by DenMurphy** [ThemeFuse/Brizy#1147]
I have tried signing up to the Brizy Affiliates via the https://brizy.io/affiliates/ page. I have a choice of "Sign Up Today", or login to "Affiliate account".

![image](https://user-images.githubusercontent.com/6964524/53080118-b1962980-3543-11e9-85bf-b0725fd6638e.png)

I tried to Sign up today, and then because I have already signed up as a Brizy Pro user, it had an error that my email was already used.

![image](https://user-images.githubusercontent.com/6964524/53080152-c672bd00-3543-11e9-8c13-efac06cf8231.png)

So I clicked the Affiliate Login button, and I filled in my Brizy account information into the Modal.

![image](https://user-images.githubusercontent.com/6964524/53080206-ddb1aa80-3543-11e9-8517-535d42423258.png)

Once I am logged in, I get redirected to my normal Brizy Pro dashboard, with no sign of Affiliate information anywhere.

![image](https://user-images.githubusercontent.com/6964524/53080058-90353d80-3543-11e9-9cdf-5842545c719a.png)

Perhaps there is a step missing here that I need to do, or at least to notify me that I am in a waiting list or something?

**Comment by DimiBaitanciuc** [comment]
Hey man, Yes you are right there is an issue with the system we are using. We've notified the developers, hopefully they address this soon. 

When you apply to be an affiliate you get redirected to create an account, once you create the account an on-boarding process is triggered and  you receive an email with next steps and we receive a notification in the back end that someone applied to be an affiliate partner. 

If you already have an account on Brizy and apply to be an affiliate, you get redirected to create account, and because you already have one that on boarding process is not triggered anymore. 

What you need to do in this case you need to email us on hello@brizy.io and we'll take it from there and basically do the on boarding manually. 

Sorry for the inconvenience.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
