### ISSUE TITLE
[Feature Request] EDD: Easy Digital Downloads Integration

### ISSUE THREAD

**Issue by codeclinic** [ThemeFuse/Brizy#1153]
Hi,

I'd really appreciate it if you could get EDD Easy Digital Downloads integrated into Brizy Pro.

Thanks.

**Comment by codeclinic** [comment]
@NataliaBB

**Comment by skynet01** [comment]
Also would love to see this integration

**Comment by codeclinic** [comment]
@skynet01 Since this has been here for 19days without any acknowledgement and issues are getting closed down and told to repost in a private message via Facebook, I'm not so sure that the Brizy team care about user input. 

Hopefully I'm wrong....

I'm currently working on some page templates that will allow EDD to be used with Brizy. Let me know if you'd like to see the result when it's finished, or just want some tips integrating it yourself.

**Comment by skynet01** [comment]
I am sure they have so much things on their plate that this is just not a priority. But yes, at least an acknowledgment would be nice.



On March 12, 2019 at 6:07:10 AM, Phill Healey (notifications@github.com) wrote:

@skynet01 Since this has been here for 19days without any acknowledgement and issues are getting closed down and told to repost in a private message via Facebook, I'm not so sure that the Brizy team care about user input.

Hopefully I'm wrong....

I'm currently working on some page templates that will allow EDD to be used with Brizy. Let me know if you'd like to see the result when it's finished, or just want some tips integrating it yourself.

**Comment by NataliaBB** [comment]
Hello Dears! @codeclinic and @skynet01 
Apologizes for my late reply! 

Be sure all issues are checked and evaluated. 
EDD added in our internal GitHub+roadmap.

Thank you! 
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
