### ISSUE TITLE
New Facebook Elements

### ISSUE THREAD

**Issue by jlydia** [ThemeFuse/Brizy#1186]
After dragging a Facebook element onto the page, we see nothing to edit.

**Comment by NataliaBB** [comment]
Hello @jlydia 
Can you give us please some examples? a screenshot of the page in the editor mode?

Thank you!

**Comment by visionlaunchers** [comment]
This is happening for us, too. We drag a FB element to the page, and nothing shows up when in the editor. However, on the front end, the elements load and show up. But there is no way to remove them from the page because they are not visible in editing mode.
![Screen Shot 2019-03-12 at 4 50 25 PM](https://user-images.githubusercontent.com/41697793/54243741-f67c0300-44e6-11e9-83ca-2dd84a39ecd4.jpg)
![Screen Shot 2019-03-12 at 4 50 22 PM](https://user-images.githubusercontent.com/41697793/54243742-f67c0300-44e6-11e9-934d-547e883056ca.jpg)

**Comment by visionlaunchers** [comment]
After submitting my comment above and continuing to work on the pages, the FB elements randomly started showing up in the editor, so I was able to remove them.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
