### ISSUE TITLE
contact form via wordpress

### ISSUE THREAD

**Issue by lilsurepbc** [ThemeFuse/Brizy#1214]
Hi, I switched my contact form to Wordpress and and after submitting the form, the form is not being delivered to the address i provided.

**Comment by NataliaBB** [comment]
Hello @lilsurepbc 
If you have also problem with wp contact form, send me please a message via our facebook chat. Mention this number issue inside 1214

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by lilsurepbc** [comment]
Okay thank you

Justin Lyons
Founder
224-307-5556

blazefamily.com

**Comment by karthik-co** [comment]
Hey! tried the wordpress chat. Doesnt really work. Any way This contact form issue can be resolved?

**Comment by NataliaBB** [comment]
Hey @karthik-co 
Yes, the contact issue form was fixed for Justin!
May I know what is the problem at your end?
Submit a ticket for me here:
https://support.brizy.io/hc/en-us

Thanks!
Regards, Natalia

**Comment by karthik-co** [comment]
Hey The problem was fixed thanks.
Best, K

karthik natarajan [+91 99232 27049 www.collectiveindependent.com]
On Thu, May 23, 2019 at 5:46 PM, NataliaBB <notifications@github.com> wrote:
Hey @karthik-co [https://github.com/karthik-co]
Yes, the contact issue form was fixed for Justin!
May I know what is the problem at your end?
Submit a ticket for me here:
https://support.brizy.io/hc/en-us [https://support.brizy.io/hc/en-us]

Thanks!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
