### ISSUE TITLE
Not able to make a section global - setting button for a block not working

### ISSUE THREAD

**Issue by Maynkmohta** [ThemeFuse/Brizy#1237]
when I try to create a Button with a Link inside a Block and click on the setting button it displays:
An error happened while trying to display this block
You can open an issue or remove this block
open the link to the video:
Link: https://cl.ly/d86a440c8c28

**Comment by NataliaBB** [comment]
Hello Mayank @Maynkmohta 
What plugins version do you have installed? We already fixed this issue in our latest version 1.0.66/0.0.19.

My Best Regards, Natalia

**Comment by Maynkmohta** [comment]
We are using Brizy 1.0.66/0.0.12. 

Here is the screenshot: https://cl.ly/1ead52686cfe

**Comment by NataliaBB** [comment]
Hey @Maynkmohta 
Please update the PRO version to the latest one 0.0.19. You have to jump straight to the 19 version so you need to download the PRO file from your Brizy account. 
1. Download the file using your Brizy account: https://brizy.io/account/login
2. After installing copy the key from your Brizy account: https://jmp.sh/6tXMMuR
3. Insert in the wp dashboard, in the Brizy tab: https://jumpshare.com/v/f4X6lagPraiwFC93NSAE

Check if the error disappeared.
Thank you!

**Comment by Maynkmohta** [comment]
@NataliaBB 
Thank you.

Tried above given steps but still, we are facing the same problem. 
Updated plugins. Screenshot: https://cl.ly/cb4ef52fcdb6
I have created the video again of the problem - check it out: https://cl.ly/d8920a0fb3ba

Regards,
Mayank

**Comment by NataliaBB** [comment]
@Maynkmohta that's strange since the last PRO update fixed this issue.
Ok, could you please send me a message via our facebook chat in order to check and fix it?
Please, mention this issue number inside -  1237


![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
