### ISSUE TITLE
Templates disappeared

### ISSUE THREAD

**Issue by juliedulong** [ThemeFuse/Brizy#1311]
I have two template pages created which, when I try to edit with the Brizy builder says the pages do not exist. See screencast: http://somup.com/cqhVVpnxIr

**Comment by crodesign** [comment]
I am also having the same issue. Brizy does function correctly on pages, just not the templates. Brizy is installed on a multisite with pro and white labeling.

**Comment by juliedulong** [comment]
How did you roll back Brizy? I am also on multisite with whitelabeling. What are you using for backups?

**Comment by crodesign** [comment]
Luckily for me, my host does daily backups. So I was able to go back to
before the issue happened.

I have not been able to update Brizy since. There are some bugs that I
can't get around. Such as it not saving posts even where Brizy is not being
used.

I will keep trying and hopefully the next update will fix those issues.

Denis Crowder
CroDesign
808-741-1514

**Comment by juliedulong** [comment]
Yes, Fingers crossed on that next update.

Thanks for your reply!

**Comment by NataliaBB** [comment]
Hello @juliedulong 
I had one user with the same problem reported via zendesk. When I tested - I deleted the template condition and added back and everything worked fine. Unfortunately, I couldn't test more, couldn't reproduce the same issue on my website (i just deleted/added back the condition). So, please, help you reproduce again this issue in order to find a fix for it. 
Send me more information here: https://support.brizy.io/hc/en-us

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
