### ISSUE TITLE
Question) How to compile page after clone the page

### ISSUE THREAD

**Issue by maheshwaghmare** [ThemeFuse/Brizy#1314]
Hi,

I have created the same ticket on wp.org support forum. See https://wordpress.org/support/topic/how-to-compile-page-after-clone-the-page/

Below is the same copy of the question.

---

I have cloned the complete page from one site to another. It clone as expected but the styling (CSS) and images are not loaded.

I have tried some below code but it not works:

```
$post = Brizy_Editor_Post::get( (int) $post_id );
$data = $post->storage()->get( Brizy_Editor_Post::BRIZY_POST, false );

// Decode current data.
$json_value = base64_decode( $data['editor_data'] );

// Custom Operations..
// ...
// ...

// Encode modified data.
$data['editor_data'] = base64_encode( $json_value );

$post->set_editor_data( $json_value );
$post->storage()->set( Brizy_Editor_Post::BRIZY_POST, $data );
$post->compile_page();
$post->save();
```

I have also used:

```
$post->set_needs_compile( true );
$post->save_wp_post();
```

Another one try:

```
$brizy_compiled_page = $post->get_compiled_page();

wp_update_post( array(
	'ID'           => $post_id,
	'post_content' => $brizy_compiled_page->get_body()
) );
```

And finally:

```
Brizy_Editor_Post::clear_compiled_cache();
```

But, After doing all this stuff it does not work. Which functions I need to use to compile and download the page.

**Comment by alecszaharia** [comment]
Mahesh, basically you did nothing wrong (try to avoid using the storage.. I will probably make that thing private )

```php
$post           = Brizy_Editor_Post::get( (int)$post_id );
$editorDataJson = $post->get_editor_data();
$editorData     = json_decode( $editorDataJson );
 // .. do something on editor data
$post->set_editor_data( json_encode( $editorData ) );
$post->set_needs_compile(true);
$post->save();
```
In order to sort this out I need to know few things:
 - Did you clone only one page or the whole site?
 - How did you clone the page? 
 - The CSS styles does not load at all or the default styles are used?


If it is possible please attach two screenshots of the page before and after.

**Comment by maheshwaghmare** [comment]
> Did you clone only one page or the whole site?

Yes, I'm cloning only a single page. Not a whole website.

> How did you clone the page?

I'm cloning the page from the 3rd party website through rest API.

> The CSS styles do not load at all or the default styles are used?

Nope. CSS not missing. Only images are not generated.

> If it is possible please attach two screenshots of the page before and after.

Please check below screenshots for reference.

Original - https://cl.ly/2101c738f213
Cloned - https://cl.ly/7d04b6d2ed95

**Comment by alecszaharia** [comment]
There are few things needed for a page to work.

1. The page it's self (the post and all the metata data)
2. The Brizy Project (the custom-post '**brizy-project**' and all the meta data that this post have )
  2.1 You should not import the project if the site has already  brizy installed.
3. All images that are used in that page. All images that brizy used in a page are marked with a meta key: **brizy_post_uid** or **brizy_attachment_uid**. The only problem I see here is that there is no easy way to know what images are used in a page.

**Comment by alecszaharia** [comment]
I also noticed that in Astra Addon you initialize the Brizy_Public_Main with two parameters.
We changed the signature of the class because of performance issues. Now there is no need to send the project.  

The code should look like this:
![image](https://user-images.githubusercontent.com/3128048/67195707-1a4ee200-f402-11e9-816f-6af6b0e74208.png)
