### ISSUE TITLE
There is an issues when i made a section as a slider . It made the page load speed huge like about 2 minute Keep up the great work thank you..

### ISSUE THREAD

**Issue by suprim12** [ThemeFuse/Brizy#137]
Waiting form submits too work too .. ..

**Comment by bagrinsergiu** [comment]
Hi,

Sergiu from Brizy here.

Can you give me a page with your problem or a screenshot ( console log + load frames )?

Every Brizy WP Page is 100% HTML + CSS + JS no one shortcode. We have a cache system implemented and every frontend load is a cached version. It is very strange that it take 2.5 min

Can you help me to solve this issue sending me more details? I added an issue in order to investigate this problem. I promise to solve 100% all issue.

Thank you
Sergiu

**Comment by bagrinsergiu** [comment]
Hi again, 

We have a big problem with Chrome extension ( Ad Blockers for example ) When Ad Blocker is on Enable Slider take a lot of time. 

Can you try in a different browser without extensions or in an incognito mode. 

Sergiu

**Comment by bagrinsergiu** [comment]
I’m closing this issue due to no reply. Feel free to re-open if I’ve misunderstood you.

Thanks for reporting.
Sergiu
