### ISSUE TITLE
can't scale background images in mobile view

### ISSUE THREAD

**Issue by RazielKanos** [ThemeFuse/Brizy#417]
if I move the blue "spot" handler around, I can adjust the background image on the desktop view quite fine, but in the mobile view it stays centered and I can't move it up or down. 

It also seems I am unable to enlarge the image. so at best i can only put a few blocks in, even if i use a vertical image

**Comment by RazielKanos** [comment]
maybe i made something wrong, but this is how it works for me:

https://jumpshare.com/v/g2sihxwpPlC7Kmh9BkW6

**Comment by bagrinsergiu** [comment]
Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Link: https://brizy.io/

Thank you.
Sergiu

**Comment by marcellefter** [comment]
Hi @RazielKanos !

This problem appear because your content is higher than image can scale and for this reason you can't set the pointer on the vertical. You can delete the image on mobile and set another one with less width and more height.
I’m closing this issue to keep the issue database slim. Feel free to re-open if you need more details.

Thank you for understanding!
Marcel
