### ISSUE TITLE
Different Brizy problems/improvements requests...

### ISSUE THREAD

**Issue by Nelmedia** [ThemeFuse/Brizy#438]
I've been asked to post my Facebook post here... So it might not be the "usual" expected format... But hopefully it will guide you in the process of improving your product...

So, here it is:

I'm doing a YouTube series right now where I create the same landing page with different page builders, to test the ease of use, development speed and overall page weight once done... The landing page that I'm replicating is that one: https://unbounce.com/landing-page-tem…/fitspo-click-through/

So far, I've tested Thrive Architect, Elementor and Oxygen 2...

I just tried to do it with Brizy... Boy it was a nightmare...! You've asked me a long time ago to give you my impressions so that you can improve the product, so here are different challenges that I faced:

1- I currently have some problems with my Chrome installation, so I was using Firefox to develop... One thing that I couldn't believe my eyes was that the text was changing lines after just few characters in a middle of a word...! Thankfully, it updated and I just saw your post that the latest version (1.0.23) have fixed this issue...;
2- In the list of major builders, it's the only one that doesn't allow me to have more advanced control for text... For example, a good web developer's practice is to put the text that we want all caps in lowercase and use CSS to put it uppercase: that gives use more flexibility if we need to change it later... Well, it's something impossible with Brizy... I know most people will not care and simple use the Caps Lock to type the text, but it shouldn't be done that way...
3- I first wanted a boxed layout: I can set the sections to be boxed, but only the content is... It's impossible to have a background image or color take just the width of the box...
4- I don't know why, but when I drag a text or copy an existing one, as soon as I edit it, it reverts back to a small black text... So, if I duplicate a text that is already formatted, as soon as I change the text, it reverts back to the default one and I need to manually re-apply the style I had...
5- Also, I created styles for paragraphs, h1, h2 and h3... But I realized that I always need, not only to click on the "T" to select the "H2" styling, for example, but I also need to click on the gear icon to select "H2" in the drop-down to have the H2 tag (by default it's always a "P")... It should be done automatically by selecting the "H2" style (or vice-versa)... Having to select it twice doubles the number of clicks and the time it takes...
6- Working with images was the worst experience I have ever seen, even with low-end page builders...! If I insert a logo, for example, in a cell, it automatically takes the full width of the cell (i.e. 100% not of the image, but of it's container)!! And also 75% of the height! So the image was cut above and below, and pixelated because it was too big... Already bad!! But even worst, then we need to try to visually change the width percentage to be the closest to the actual image width...! No possibilities of at least entering the right pixel values... No, just %! Unbelievable...! And the first time that I did the 3 columns in the "Start training today" section, after creating the first column I duplicated it, with the image inside it of 40% width... The duplicated column's image was then 40% of the size of the previous one!! Trying to resize it was making the image awfully pixelated... I had to delete and re-insert it again to "solve" that...!
Then the "Featured class" section... I was never able to remove the space totally on the second column of each row, so the borders are not aligned with the image and the first column... I've set all the paddings and margins to 0 everywhere, even try negative margins, nothing would work...
7- Of all the 4 builders that I've tested so far, with Elementor I had to write some CSS to allow me to make the little image and the quotes floating left in the "Meet the owner" section... But even then, with Brizy there is absolutely no place to enter any CSS or class or ID... So, not an option...
8- So, I tried to use a CSS plugin: first I tried CSS Hero... Wasn't working very well... So, I tried with my favorite one: Microthemer... I then realized why it was so hard: there's an incredible amount of nested divs for one element, even with empty divs only there for overlays or similar... Microthemer allows me to see the code to target the right element, but not everyone understands code...
9- I know that one "strength" (at least for some people) is that the controls are just above the element the we are modifying, but when I tried to change the logo near the top of the page, since there wasn't enough space for the more advanced tools (gear icon), the box was under, hence completely covering the image: really hard to modify it when it's under that box...! And because of the size of that bar, it is so limited the number of items that are on it that I almost always have to click the gear icon and then the "More advanced" link that I finally end up clicking more than with other page builders...
10- If we use pre-built blocks, it might be better, but the default blank one is way too limitating...

I was hoping that at least the Pro version would give more control, but looking at the sales page, there's nothing about better typography or image control...

So, since the beginning I'm saying that I won't use Brizy before version 2, as there are too many things missing... I rejoice to see how many updates you guys make, but it's still very far from their competitors... I really hope that it will become a better product (I even bought the lifetime Pro version), but for now, I would say that for my needs (more a developer than a designer, so need to replicate a design that I'm provided with) I would probably give it a score of 5 out of 10...

Hope you will see my critics as constructive and it will help you make a better product out of it...

I don't know how long I'll keep the page active and the Brizy plugin, as it is a test site for all the videos in the serie, but if you want to take a look, here's the link of my final output with Brizy: https://nelmedia.ca/…/editors/land…/landing-page-brizy-test/
As a comparison, here's the result with my favorite one: Thrive Architect: https://nelmedia.ca/…/landing-page/landing-thrive-architect/

**Comment by bagrinsergiu** [comment]
Hi,

Thanks for details. 

1/  I currently have some problems with my Chrome installation, so I was using Firefox to develop... One thing that I couldn't believe my eyes was that the text was changing lines after just few characters in a middle of a word...! Thankfully, it updated and I just saw your post that the latest version (1.0.23) have fixed this issue...;

This issue was fixed in 1.0.23. 

---

2/  In the list of major builders, it's the only one that doesn't allow me to have more advanced control for text... For example, a good web developer's practice is to put the text that we want all caps in lowercase and use CSS to put it uppercase: that gives use more flexibility if we need to change it later... Well, it's something impossible with Brizy... I know most people will not care and simple use the Caps Lock to type the text, but it shouldn't be done that way...

I'm agree that Caps lock must be an interesting feature thanks for suggestion. 

"a good web developer's practice is to put the text that we want all caps in lowercase" - What about designers or non-coders? Here at Brizy we want a balanced product for Designers, non-coders and developers. I prefer Sketch compared to Photoshop.

---

3/ I first wanted a boxed layout: I can set the sections to be boxed, but only the content is... It's impossible to have a background image or color take just the width of the box...

10-15 years ago each web page max height was 600-800px, one website == a lot of pages and sidebars with Full height BG image or BG Color. In 2018 internet is completely different 1 landing page can include 10 pages from 2005 (each block is a new page). Each bock is a new entity in 2018 equal with 1 page in 2005. 

Each block == New Entity == Custom BG + Content 

1. Homepage: https://jmp.sh/dXmgdnw
2. Services page: https://jmp.sh/7Hm4qFE
3. Testimonials page: https://jmp.sh/xnsHYSi
4. Pricing page: https://jmp.sh/zEMtcow

A boxed page with BG Color and Image can be archived with a theme as Astra or Ocean WP. 

---

4/ I don't know why, but when I drag a text or copy an existing one, as soon as I edit it, it reverts back to a small black text... So, if I duplicate a text that is already formatted, as soon as I change the text, it reverts back to the default one and I need to manually re-apply the style I had...

There are 2 concepts here:

1. when you want to copy a lot of small bits of text that have only one style
2. when you want to copy a bigger chunk of text that contains multiple styles, multiple Hs maybe, P, etc.

How it works now the text is stripped of all the styling and takes the styling of the text you are pasting into. This works best for the 1 I've mentioned above.

Unfortunately, it doesn't work very well with the second 2 where you copy multiple style texts.

I personally don't like styles to come from somewhere else, and always run the text through a notepad or something to strip the stying but I understand that in your case is not ideal.

https://www.facebook.com/groups/brizy/permalink/241906956573184/?comment_id=242059783224568&notif_id=1528665759883720&notif_t=group_comment_follow&ref=notif

---

5/ Also, I created styles for paragraphs, h1, h2 and h3... But I realized that I always need, not only to click on the "T" to select the "H2" styling, for example, but I also need to click on the gear icon to select "H2" in the drop-down to have the H2 tag (by default it's always a "P")... It should be done automatically by selecting the "H2" style (or vice-versa)... Having to select it twice doubles the number of clicks and the time it takes...

We plan to fix in future. ( we don't have a solution for this right now )

---

6/ Working with images was the worst experience I have ever seen, even with low-end page builders...! If I insert a logo, for example, in a cell, it automatically takes the full width of the cell (i.e. 100% not of the image, but of it's container)!! And also 75% of the height! 

I will try to explain why it is working in this way. It is hard to find one solution for all cases. In our cases image must work with logos, images, galleries, bg, ...

All features in Brizy is build by % of total (UX) for example if a specific page include 36 images (10 img, 5 bg, 20 gallery and 1 logo) Logo experience is ignored in case it is not possible to archive a better result for the same element in our case Image. Logo means in our case only 3% from total.   

---

So the image was cut above and below, and pixelated because it was too big... Already bad!! 

You are not right. All images are resized automatically for Desktop, Tables and Mobile with Normal and Retina sizes for Mobile and Preview mode. Screenshot: https://jumpshare.com/v/A1ykveri83q0h9g7M1YB 

---

But even worst, then we need to try to visually change the width percentage to be the closest to the actual image width...! No possibilities of at least entering the right pixel values... No, just %! 

Again you are not right: https://jmp.sh/F16saI1

---

Unbelievable...! And the first time that I did the 3 columns in the "Start training today" section, after creating the first column I duplicated it, with the image inside it of 40% width... The duplicated column's image was then 40% of the size of the previous one!! Trying to resize it was making the image awfully pixelated... I had to delete and re-insert it again to "solve" that...!

Again you are not right: https://jmp.sh/zYj8ihc

---

Then the "Featured class" section... I was never able to remove the space totally on the second column of each row, so the borders are not aligned with the image and the first column... I've set all the paddings and margins to 0 everywhere, even try negative margins, nothing would work...

Change Column margin padding to 0px and image margin, padding to 0: https://jmp.sh/RX0K144

----

7/  Of all the 4 builders that I've tested so far, with Elementor I had to write some CSS to allow me to make the little image and the quotes floating left in the "Meet the owner" section... But even then, with Brizy there is absolutely no place to enter any CSS or class or ID... So, not an option...

Under element settings it is possible to add CSS class: https://jmp.sh/xeP1cH0

----

So, since the beginning I'm saying that I won't use Brizy before version 2, as there are too many things missing... I rejoice to see how many updates you guys make, but it's still very far from their competitors...

Brizy version is 24 :) https://jmp.sh/79GkDC2 

Brizy is a 2 month plugin let's discuss in 3 months. I'm 100% sure it will include 80-85% Elementor  features.  

Thanks for your time and details

Cheers, Sergiu

**Comment by Nelmedia** [comment]
Hi,

Want to come back on some of your comments:
Point number 6:
- I'm not sure I understand your point about different image sizes and the logo representing 3% of the images... So what? You don't consider the logo just because you have only one?
Point 6b:
- You say I'm wrong about the images being cut... Well, look at my video review and you'll see what happens: it is cut because by default the image height wasn't 100% (depends on the pixel ratio) (see https://www.youtube.com/watch?v=RKqViidYGB8&t=699s)
Point 6c:
- I'm saying that you can only use "%" and not "px"... and you tell me I'm wrong and shows a video that exactly proves my point: there is only "%"...!
Point 6d:
- About duplicating a column and the image being resized the wrong way... Again, you tell me I'm wrong and you put a video showing that you probably use a big image that gets resized depending on the need of the screen... Great feature, but not my point at all...! I'm using an image that is smaller than the width of the column and it's not resized well when I duplicate the column... Again, look at my video review (https://www.youtube.com/watch?v=RKqViidYGB8&t=699s) and you'll see what I mean (I had to delete one image and recreate it because of the way it was working)... The behavior might be intentional, but it doesn't work in the workflow that I show (that is the same one I used with Thrive Architect, Elementor and Oxygen without any issue)...

Point 7:
Yes, there is a place to enter a CSS class (no ID), but there's no place to actually enter the CSS code that will modify that CSS class we have entered... We need to go back to WP's tools to do it... I've been told, though, that it's coming in a later release...

About "version 2", you mention that Brizy is now on version "24"... Well, it's "1.24", not "2.x", so it's not version 2 yet... These are minor updates and bug fixes, not a major new release... So, when I'm talking about that, I'm talking about the next major release (2.x)... Like I say in the video, I just feel sometimes that you release some features that are "unfinished", maybe to show your users your progress... Just as an example: I just learned today that you have a form element, but you don't support checkboxes and radio buttons (and other things I guess)... I believe that you should have waited until all the regular form elements were ready before releasing the form element, and not push something that finally, as stated in a reply, you still need to use another plugin if you want to have a confirmation checkbox... But, that's just an opinion here and yours is as good as mine...

Thank you,
Nelson
