### ISSUE TITLE
responsive column setting

### ISSUE THREAD

**Issue by ash-f** [ThemeFuse/Brizy#45]
I need responsive column setting like other page builders.

i.e.
set specific column width at specific break point manually.

**Comment by MaxZiebell** [comment]
I must second this request. In custom design or even in design blocks from Brizy with icon in columns we need to be able to set the columns in mobile to a percentage instead of defaulting to 100%. For example when using Icons in columns they could easily sit two on each row on mobile and not make the page too long on mobile.

**Comment by bagrinsergiu** [comment]
Hi All, 

This option is planned for next version 1.0.45. 
Thanks for suggestions.

Sergiu
