### ISSUE TITLE
WooCommerce elements ad a random string at the top of the page

### ISSUE THREAD

**Issue by quantumleap33** [ThemeFuse/Brizy#49]
There must be a bug on all WooCommerce elements. They add a "Read more" /> Read more"> Read more"> " text at the top of the page.

**Comment by quantumleap33** [comment]
There seems to be a conflict with the Woocommerce Social Media Share Buttons plugin.

**Comment by DimiBaitanciuc** [comment]
Thanks for letting us know.

**Comment by quantumleap33** [comment]
It happens when the "Automatically add open graph meta data to site header" checkbox is selected on the plugin's settings.

**Comment by marcellefter** [comment]
Hi @quantumleap33 

I've been notice that this problem comes from Astra theme, plugin itself wasn't update up 2 years and might have problem. You can try to add this code in your theme **functions.php** file
```php
add_filter('get_the_excerpt', 'theme_custom_the_excerpt');
function theme_custom_the_excerpt($excerpt) {
    return strip_tags($excerpt);
}
```
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you
Marcel
