### ISSUE TITLE
Pro Version Activation

### ISSUE THREAD

**Issue by ShajumonP** [ThemeFuse/Brizy#500]
I have create a site with free version. How can I activate Pro.

**Comment by NataliaBB** [comment]
Hi @ShajumonP!
Please follow these steps in order to activate Pro:
1. Login into your Brizy.io account and download the Brizy Pro plugin .zip
2. In your WP dashboard, upload and install the .zip file.
3. Activate the plugin.

This is it. You can continue editing pages with Brizy builder (even those created already)

Regards, Natalia

**Comment by Fruitnoob** [comment]
The pro download does not seem to do anything. It is installed along with the Brizy plugin but nothin seems to change.

Running the site on localhost with no other plugins installed.

**Comment by NataliaBB** [comment]
Hey @ShajumonP 
I’m closing this issue to keep the issue database slim. Feel free to re-open if you need more details.

Thank you!
Regards, Natalia
