### ISSUE TITLE
Text links in editor settings but not present on live page

### ISSUE THREAD

**Issue by ouquinn** [ThemeFuse/Brizy#556]
I continue to have problems with links. Currently, I have links on text, but on the live page, it shows no link even though in the editor the link is clearly still in the settings.

**Comment by NataliaBB** [comment]
Hi @ouquinn 

Thanks for reporting this! 

Please send me a short message via our FB chat and mention this issue inside:
https://jumpshare.com/v/i5bFUpOUtAAI3EVSuMMJ
Web Page: https://brizy.io

P.S This issue should be fixed by our update, planned for today. But let's check more carefully this problem at your site.

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
