### ISSUE TITLE
styling cleanup button for text element

### ISSUE THREAD

**Issue by ash-f** [ThemeFuse/Brizy#57]
it would be nice to have this when fiddled text too much.
source code might be span hell.
cleanup button saves from it.

**Comment by bagrinsergiu** [comment]
Hi @ash-f 

We added 3 improvements for text editor in last 30 days. Can you check it Styling cleanup is working for you?

**Comment by ash-f** [comment]
How to clean up? 
Automatic or there's a button for it?

**Comment by bagrinsergiu** [comment]
Automatic

**Comment by ash-f** [comment]
Sorry I couldn't get what your screencast is trying to tell.
Point I was trying to tell is often seen on TinyMCE, that when repeating styling text over and over, html will be messed with bunch of unnecessary span tags(or a, strong and so on)
So I worried same thing on Brizy.

**Comment by bagrinsergiu** [comment]
There are 2 concepts here:

1. when you want to copy a lot of small bits of text that have only one style
2. when you want to copy a bigger chunk of text that contains multiple styles, multiple Hs maybe, P, etc.

How it works now the text is stripped of all the styling and takes the styling of the text you are pasting into. This works best for the 1 I've mentioned above.

Unfortunately, it doesn't work very well with the second 2 where you copy multiple style texts.

I personally don't like styles to come from somewhere else, and always run the text through a notepad or something to strip the stying but I understand that in your case is not ideal.

https://www.facebook.com/groups/brizy/permalink/241906956573184/?comment_id=242059783224568&notif_id=1528665759883720&notif_t=group_comment_follow&ref=notif

**Comment by ash-f** [comment]
Not about copy&paste.
TinyMCE messes up html markup without using copy&paste but just using styling buttons.

Is this this applicable to Brizy?

**Comment by bagrinsergiu** [comment]
We don't use  TinyMCE. Brizy text widget is powered by Quilljs - https://quilljs.com 

Comparison with TinyMCE: https://quilljs.com/guides/comparison-with-other-rich-text-editors/

1. Quill maintains an internal document model and does not rely on the DOM as the source of truth, allowing it to offer far more powerful and relevant APIs for text editing.

2. It allows customization and new additions of formats and content. Quill considers the web as a target output, not just paper. Therefore, in additional to supporting traditional formats commonly found in word processors (like bold, italics and lists), Quill allows the definition of entirely new formats and content not previously imagined. Quill’s users have already added customizations to embed slide decks, interactive checklists and 3D models.

3. Both Quill and ProseMirror implement and maintain a data model to operate on with APIs, instead of allowing users to modify DOM directly.

**Comment by ash-f** [comment]
Thank you.
As long as html won't have unnecessary garbage tags, it will be fine.

**Comment by bagrinsergiu** [comment]
I'm closing this issue to keep the issue database slim. Feel free to re-open if I've misunderstood you.

Sergiu
