### ISSUE TITLE
Cannot Update the Page after edit

### ISSUE THREAD

**Issue by motokimotoki** [ThemeFuse/Brizy#626]
I have made changes to my page and press update but the circle goes around but does not change after waiting for a while.
But there are other pages which updates are successful but about half of the pages within the same website is not able to update.

**Comment by NataliaBB** [comment]
Hi @motokimotoki 
Natalia here!

Please send me a message via our Facebook Chat in order to check and fix this bug asap.

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45802149-a56d1e00-bcbe-11e8-9062-2682e4f1b130.png)

Thank you
Regards, Natlaia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
