### ISSUE TITLE
Fatal error: Class 'Twig_Loader_Array' not found 

### ISSUE THREAD

**Issue by tzs007** [ThemeFuse/Brizy#710]
I just installed Brizy on my site with v4.9.8 but I got this error when I want to edit a page:

Fatal error: Class 'Twig_Loader_Array' not found in /chroot/home/.../html/wp-content/plugins/brizy/twig-engine.php on line 40

**Comment by NataliaBB** [comment]
Hi Zsolt @tzs007 

Natalia here, Brizy team!
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by perlatsp** [comment]
@tzs007 did you found a fix for this ?
I am having the same issue. 
I am using PHP 5.6.

**Comment by dinuionut** [comment]
@perlatsp Maybe a bit too late now, but I hope that it helps somebody else.
For me there was an old composer config file somewhere in the same directory, which was preventing Twig from loading. It escaped unnoticed because the WP installation was pretty old. After removing it everything worked fine.
It can also happen if you don't have Twig installed on the server, obviously.
