### ISSUE TITLE
What is the recommend theme to use with Brizy?

### ISSUE THREAD

**Issue by curiousprojects** [ThemeFuse/Brizy#780]
What theme would work perfect with Brizy?

**Comment by kpjjf1** [comment]
The free version of Ocean WP works well.

**Comment by NataliaBB** [comment]
Hey @curiousprojects 
Astra, Ocean WP, The Core  - these are the most tested themes by our team.
From my experience, users have a lot of different themes which also works with Brizy.
But, if you notice a bug or a specific issue on your theme, please feel free to report on our Facebook chat:

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

We can fix it at your end also we often get in contact with the theme author in order to find a good solution.

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
