### ISSUE TITLE
Links - conflict with Gutenberg

### ISSUE THREAD

**Issue by lowfields** [ThemeFuse/Brizy#830]
I have noticed that when Gutenberg is active links within text act as though a  line break has been inserted immediately after them - they are forced onto the line below. As soon as I turn Gutenberg off the links behave correctly.

**Comment by NataliaBB** [comment]
Hi @lowfields 
Natalia here!
This bug was fixed in our 1.0.40th Version. But if you still have this issue at your side, please give me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
