### ISSUE TITLE
Problem with activation

### ISSUE THREAD

**Issue by DiLJEC** [ThemeFuse/Brizy#870]
Hi,

I have problem with activation. After I hit activation button wordpress show this message:

Parse error: syntax error, unexpected T_USE, expecting T_FUNCTION in /hermes/bosnacweb01/bosnacweb01av/b624/ipg.gradosic/www_Grga_eu/wp-content/plugins/brizy/admin/migrations/shortcodes-mobile-one-migration.php on line 5

Please help

**Comment by bagrinsergiu** [comment]
Hi,

Error is on line:  use Brizy_Admin_Migrations_PostsTrait;

Trait was added in PHP 5.4 . Brizy minimal PHP version is 5.4  I need more details in order to investigate this issue.

Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu
