### ISSUE TITLE
Cannot Add Or Remove Accordion Items

### ISSUE THREAD

**Issue by bytesource** [ThemeFuse/Brizy#922]
I know adding an item to an accordion should work, because @DimiBaitanciuc sent me a screenshot on Brizy's FB group: https://jumpshare.com/v/ktWcolrfzb0vUAZuY31a 

However, in my case right clicking on an item an pressing 'duplicate' only duplicates the complete accordion. 

Dimitrie suggested this might be a bug or a conflict with one of the installed plugins:

> Must be either a conflict with a plugin you have installed or maybe a bug and needs to be reported on our Github

If you like to take a look at the particular page, I can set up an account with admin rights for you. Just let me know where to send the details privately.

My current Brizy installation:

- Brizy 1.0.48
- Brizy 0.0.12 
- OceanWP

**Comment by bagrinsergiu** [comment]
Hi Stefan,

Right Click Dropdown Duplicate/ Delete options is for entire element. In order to Duplicate/ Delete an accordion or tabs item click in Accordion/ Tabs item and click on duplicate icon from toolbar: https://jmp.sh/XD3dONM

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu

**Comment by bytesource** [comment]
Thanks for sending me this video. It's working now. 

Thanks a lot again!
